### ISSUE TITLE
phone numbers from other countries

### ISSUE THREAD

**Issue by skyride99** [joshswan/react-native-autolink#10]
if i have text with a phone number it does not show as underlined

for example "09464493201", and no intent. Does this only work with US phone number

**Comment by joshswan** [comment]
Unfortunately it looks to be US-only and only when it's in this format: (XXX) XXX-XXXX. You can feel free to chime in on gregjacobs/Autolinker.js#95 and gregjacobs/Autolinker.js#128 as I'm guessing they're having trouble coming up with regex that would work for a wider variety of number formats. 

Within the Autolinker.js file that gets installed with this package, you can also update the regex yourself on line 3017.

**Comment by skyride99** [comment]
Ok good enough. The RegEx works thanks for your help.

**Comment by tangkunyin** [comment]
@joshswan thanks your framework.By changing the source code of `Autolinker.js` , my problem solved.

**Comment by joaopiopedreira** [comment]
Hi @joshswan , it looks like we can override the phone regex directly in your `src/matchers.js` file. I've done it in [my branch](https://github.com/joaopiopedreira/react-native-autolink) and it works like a charm. The idea is to add a regex by country and then merge them all when invoking the `phone` autolinker.

To add a new country, we would add the corresponding regex to this object (in `src/matchers.js`):
```
// To include a new country, find it's ISO Alpha 2 code at http://www.nationsonline.org/oneworld/country_code_list.htm
const regexByCountry = {
  US: /(\([0-9]{3}\)[\s-]|[0-9]{3}[\s-])[0-9]{3}[-\s][0-9]{4}/g,
  GB: /(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)?(44)\)?[\s-]?(? (...),
  FR: /(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)?(44)\)?[\s-]?(? (...),
  PT: /(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)?(44)\)?[\s-]?(? (...),
  IE:  /(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)?(44)\)?[\s-]?(? (...),
  DE:  /(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)?(44)\)?[\s-]?(? (...),
};
```

Our phone override would then look like this:
```
  // Phone override
  {
    id: 'phone',
    regex: combinedRegex(['US', 'GB', 'FR', 'PT', 'IE', 'DE']),
    Match: Autolinker.Util.extend(Autolinker.match.Match, {
      constructor(cfg) {
        Autolinker.match.Match.prototype.constructor.call(this, cfg);
        this.number = cfg.phone;
      },
      getType() {
        return 'phone';
      },
      getNumber() {
        return this.number;
      },
      getAnchorHref() {
        return `tel:${this.number}`;
      },
      getAnchorText() {
        return this.matchedText;
      },
    }),
  },

``` 

Is this something you'd want to include in your package? Should I submit a PR? Cheers
