### ISSUE TITLE
expanding text

### ISSUE THREAD

**Issue by mschipperheyn** [joshswan/react-native-autolink#11]
I need to be able to x lines and then have a 'Read more' style link to 'open' the rest. There is a component for this, but of course, I would like to combine it with autolink. Any suggestions?

**Comment by joshswan** [comment]
If you know the number of lines you want to show while collapsed, you can do this pretty simply:
```javascript
class ReadMoreExample extends Component {
  constructor(props) {
    super(props);

    this.state = {
      readMore: false,
    };

    this.onPressReadMore = this.onPressReadMore.bind(this);
  }

  onPressReadMore() {
    this.setState({
      readMore: true,
    });
  }

  render() {
    return (
      <View>
        <Autolink
          text={text} // Set text prop appropriately
          numberOfLines={this.state.readMore ? undefined : 2} // Show two lines or all if readMore
        />
        // Show read more button until pressed
        {!this.state.readMore ? (
          <TouchableHighlight onPress={this.onPressReadMore}>
            <Text>Read More</Text>
          </TouchableHighlight>
        ) : null}
      </View>
    );
  }
}
```

**Comment by mschipperheyn** [comment]
Alright. I guess I will have to look into how to determine when there are more lines in the text that `numberOfLines`. Because obviously, Read More should only be displayed when there is something more to read. I imagine here lies the challenge.

**Comment by joshswan** [comment]
Good point. If you can't guarantee there will be enough text to overflow, there's a bit of a problem. Current best practice seems to be to set the number of lines to undefined/null first and measure the height. Then set the number of lines to the max you want to allow, and measure the height again to see if it was shortened. At that point you can add the "read more" button. Maybe something like:
```javascript
class ReadMoreExample extends Component {
  constructor(props) {
    super(props);

    this.state = {
      expandedHeight: 0,
      hasMore: false,
      readMore: false,
    };

    this.onLayout = this.onLayout.bind(this);
    this.onPressReadMore = this.onPressReadMore.bind(this);
  }

  onLayout(e) {
    const s = {};

    if (e.nativeEvent.layout.height >= this.state.expandedHeight) {
      s.expandedHeight = e.nativeEvent.layout.height;
    } else if (!this.state.readMore) {
      s.hasMore = true;
    }

    this.setState(s);
  }

  onPressReadMore() {
    this.setState({
      readMore: true,
    });
  }

  render() {
    return (
      <View>
        <Autolink
          text={text}
          numberOfLines={(this.state.readMore || !this.state.hasMore) ? undefined : 2}
          onLayout={this.onLayout}
        />
        {this.hasMore && !this.state.readMore ? (
          <TouchableHighlight onPress={this.onPressReadMore}>
            <Text>Read More</Text>
          </TouchableHighlight>
        ) : null}
      </View>
    );
  }
}
```

Unfortunately, the full length of the text block will initially render before being truncated but there doesn't seem to be a workaround for that currently unless you're comfortable building a native component that exposes whether the text is truncated in some way.

**Comment by mschipperheyn** [comment]
Thanks for the suggestions. I will have a go with this. Initially rendering the text is not the problem as long as you don't get screen flashes or jitter (which is likely). I can also foresee some issues with the SGListView that I'm using for this as well. It renders empty boxes to make infinite lists memory efficient under the contract that the size of the box doesn't change based on the inner working of the box.

**Comment by joshswan** [comment]
Yeah, I'd imagine you're going to get some flicker and probably some issues with an `SGListView`. Frankly, I don't know if I'd use this hack in any sort of list as it'll probably make it jumpy and not very performant. You may want to look into displaying the expanded text on a separate page after clicking on a row since RN really doesn't seem to handle this use case.
