### ISSUE TITLE
Incorrect usage of canOpenUrl?

### ISSUE THREAD

**Issue by raffij** [joshswan/react-native-autolink#16]
I believe Linking.canOpenUrl returns a promise rather than a boolean so this will never work?
https://github.com/joshswan/react-native-autolink/blob/master/src/index.js#L62

Looks like the logic for fallbacks needs to be moved to the onPress function. Either by getURL passing an array of urls if there's a fallback, or a getFallback function such as in this fork?

https://github.com/conversocial/react-native-autolink/blob/master/src/index.js

**Comment by joshswan** [comment]
Agreed. Not sure how that happened. I'll try to look into asap, or feel free to submit a PR if you're interested.

**Comment by joshswan** [comment]
Fixed in v1.0.0. Thanks for letting me know!
