### ISSUE TITLE
Support for textinput field

### ISSUE THREAD

**Issue by Thanmai-C** [joshswan/react-native-autolink#20]
Could have been nice if this would have been textinput where in there is dynamic entry of text data, rather than giving autolink component stored text.
I need a similar kind of thing as in while user is typing in the text field, the text automatically links to URLs, phone numbers, emails,hashtags. etc.
Please help regarding this.

**Comment by joshswan** [comment]
As far as I know, RN doesn't support elements within a `TextInput` so there's no way to wrap the links and listen for clicks. Given that the `value` prop for the `TextInput` component is a `string`, I don't think what you're asking for is possible without doing some sort of trickery, like overlaying a `Text` element or as they type.

**Comment by Thanmai-C** [comment]
Or is there any way that we can change the color of the text with hashtag/email/, without clicks only.
Just change the color on the TextInput field.

**Comment by joshswan** [comment]
I believe styles apply to the entire `TextInput` as well so you can't apply colors to just one part of the text. Maybe I'm wrong, but as far as I know, there's no way to do what you're asking without another component

**Comment by Thanmai-C** [comment]
Ok will check
If you get to know how to do it, please share
