### ISSUE TITLE
Can I open the iphone system address book? If you can write a url how to write quickly and ask you to teach me?

### ISSUE THREAD

**Issue by ma569322307** [joshswan/react-native-autolink#27]
Can I open the iphone system address book? If you can write the url how to write quickly, I beg you to teach me. I want to go to the address book and click on one of the contacts to return the phone number.

**Comment by joshswan** [comment]
I'm not aware of a way to link people to the contacts app. Additionally, that functionality isn't implementable through app linking and this really isn't the right package for that sort of thing. I recommend you take a look at [react-native-contacts](https://github.com/rt2zz/react-native-contacts) or something similar so your app can get access to the user's contacts directly and you can display a list within your own app.
