### ISSUE TITLE
support numberOfLines property

### ISSUE THREAD

**Issue by mschipperheyn** [joshswan/react-native-autolink#3]
Hi, 

I would like to ask you to support numberOfLines on Text so that we can use that functionality.

**Comment by joshswan** [comment]
Sounds like a good enhancement. Happy to accept a PR or I'll work on it when I have a bit of time

**Comment by joshswan** [comment]
Actually that was a pretty simple one, haha. I haven't had time to test it yet, but I'll do that later and get it published to npm. For now you can install directly from `joshswan/react-native-autolink` using npm and check it out.

**Comment by joshswan** [comment]
Published to npm (v0.4.0)

**Comment by mschipperheyn** [comment]
thx
