### ISSUE TITLE
custom pattern

### ISSUE THREAD

**Issue by mammad2c** [joshswan/react-native-autolink#30]
hi, how can i use my custom regex and a custom rendering item?

**Comment by joshswan** [comment]
Custom rendering can be accomplished using the `renderLink` prop which controls how to output each detected link, and of course the `style` prop to control the overall `Text` style. Custom regex isn't supported yet (#25), but you can see how the LatLng matcher is implemented [here](src/matchers.js) and do something similar. PR's are welcome as I've been really busy and haven't had a chance to work on the custom phone number support as planned.
