### ISSUE TITLE
Hashtag Function go to other link

### ISSUE THREAD

**Issue by geraldymp** [joshswan/react-native-autolink#31]
<Autolink
              text={name + ' ' + comment}
              style={styles.commenttext}
              hashtag = 'twitter'
            />

I am using this code right now and adding hashtag make every hashtag automatically blue. It's good feature, but i want to change the destination, so whenever I click the hashtag i won't open twitter, but other link I preferred.
Is this possible?

**Comment by joshswan** [comment]
Use the `onPress` prop to pass your own custom handler function and send users wherever you please. See the [README](https://github.com/joshswan/react-native-autolink/blob/master/README.md) for details.

**Comment by geraldymp** [comment]
thanks, it solved my problem.
now i tried to change the destination with navigation, like this =

<Autolink
              text={name + ' ' + comment}
              style={styles.commenttext}
              hashtag='instagram'
              onPress={() => this._onPressRight()}
            />

_onPressRight() {
    this.props.navigation.navigate('SearchUser');
  }

But it doesnt work. Is there any way I could make this to 'SearchUser' ?
