### ISSUE TITLE
Add support for not providing a default style

### ISSUE THREAD

**Issue by hughbe** [joshswan/react-native-autolink#34]
I want to make links bold and inherit the color of a parent text element, e.g.

```jsx
<Text style={termcardIntroductionStyles.textContainer}>
    <Text Welcome{'\n'}</Text>
    <Autolink text="Some introductory text" linkStyle={{fontWeight: 'bold'}} />
</Text>

...
const termcardIntroductionStyles = StyleSheet.create({
    textContainer: {
        color: '#fff'
    }
});
```

As you can see below, the text is rendered blue, but I ideally want the text to inherit the parent text color without duplicating `color: '#fff'` in the style
![50058620_2089767014611937_5036807524972494848_n](https://user-images.githubusercontent.com/1275900/51249905-c142b100-198c-11e9-927a-0021ae0bef28.jpg)

The following code:
```js
  renderLink(text, match, index, textProps) {
    const truncated = this.props.truncate ? this.constructor.truncate(text, this.props) : text;

    return (
      <Text
        {...textProps}
        key={index}
        style={[styles.link, this.props.linkStyle]}
        onPress={() => this.onPress(match)}
        onLongPress={() => this.onLongPress(match)}
      >
        {truncated}
      </Text>
    );
  }
```

The code can be fixed by having some prop that says "don't use the default style, use the given `linkStyle` only"

**Comment by joshswan** [comment]
Just released `v1.6.0` and if you provide a `linkStyle`, it will no longer apply any default styles so you won't have to override them.
