### ISSUE TITLE
Support latest improvements of Autolinker

### ISSUE THREAD

**Issue by cliren** [joshswan/react-native-autolink#35]
Autolinker has many improvements is currently at v3.0.2, checking to see if there are any plans to upgrade the dependency?

**Comment by joshswan** [comment]
Yep. Autolinker is updated on master already. I'm working on adding support for the new hashtag and mention options

**Comment by joshswan** [comment]
`v1.7.0` is out on npm with support for Facebook hashtag links, SoundCloud username/mention links, and the `stripTrailingSlash` option for URL text!
