### ISSUE TITLE
1.7 throws Super expression must either be null or a function

### ISSUE THREAD

**Issue by jpaas** [joshswan/react-native-autolink#36]
When I upgraded to 1.7, it started throwing this exception: `Super expression must either be null or a function` when importing it.

**Comment by appli-intramuros** [comment]
@jpaas I have exactly the same problem ...

We need help :)

**Comment by jpaas** [comment]
Thanks @joshswan !

**Comment by joshswan** [comment]
No problem :) `v1.7.1` will be published shortly
