### ISSUE TITLE
onPress not working while using renderLink

### ISSUE THREAD

**Issue by Cosnavel** [joshswan/react-native-autolink#39]
I started wondering, why I can't get the onPress function working. On the moment I got the renderLink function, the onPress isn't available anymore.

` <Autolink
                    text="This is the string to parse for urls https://frank/4, phone numbers"
                    stripPrefix={true}
                    onPress={link => console.log(link)}
                    phone={false}
                    email={false}
                    renderLink={link => {
                       tempLink = link;
                       tempLink = tempLink
                         .substring(tempLink.indexOf("/"))
                        .substring(1);
                       console.log(tempLink);
                       return link.substring(0, link.indexOf("/"));
                     }}
                    showAlert={false}
                  />`

**Comment by joshswan** [comment]
Currently, `renderLink` assumes you're doing a completely custom link implementation, including your own `onPress` handlers. This provides maximum flexibility but obviously requires a bit more effort to implement.

Take a look at how the default `onPress` handler looks to see how your version should currently be implemented and let me know if you have suggestions on how to make it easier (while still being flexible).

**Comment by Cosnavel** [comment]
Did you got any Example how it could work ?

**Comment by joshswan** [comment]
Just as it does in the default `onPress` handler:
```javascript
<Autolink
  renderLink={(text, match, index) => (
    <Text
      key={index}
      onPress={() => doSomething(match)}
    >
      {text}
    </Text>
  )}
/>
```

**Comment by Cosnavel** [comment]
Ok thank you. That makes a lot of sense. I will think about a better implementation. 

My Solution: 
`<Autolink
                    text={this.props.data.text}
                    stripPrefix={true}
                    phone={false}
                    email={false}
                    style={{ fontSize: 20, color: "purple" }}
                    renderLink={(text, match, index) => {
                      return (
                        <Text
                          key={index}
                          style={{ color: "blue", fontSize: 20 }}
                          onPress={() => alert(text)}
                        >
                          {text.substring(0, text.indexOf("/"))}
                        </Text>
                      );
                    }}
                    showAlert={false}
                  />`
