### ISSUE TITLE
Why does the project use src/ and lib/ dirs?

### ISSUE THREAD

**Issue by mikelambert** [joshswan/react-native-autolink#4]
Seems like it'd be easier to just stick src/index.js in the root directory as the main/only js file. I see gulp file that transpiles with babel, but that's basically already done with any/all react-native-* modules these days anyway, right?

**Comment by joshswan** [comment]
There was originally a reason ages ago, I believe. But you're right, there's no point in it now. I'll remove the `lib/` directory and the build step in the next release.

**Comment by joshswan** [comment]
All gone on the `master` branch
