### ISSUE TITLE
Respect Newlines

### ISSUE THREAD

**Issue by XaviSmith** [joshswan/react-native-autolink#47]
I'm using the Autolink library to parse out links/phone numbers for certain blobs of text that may contain them, however it looks like every newline gets parsed out, regardless of if I use multiple lines, add \n, <br>, <p> etc etc. 
Example:

> This is a test for newlines
> 
> 1. some text.\n
> 2. some other text

becomes

> This is a test for newlines, 1. some text.\n 2. some other text

How do I fix this?

**Comment by joshswan** [comment]
Without a full code example, I can't really say much. However, the following works just fine with respect to newlines so I believe the library is working correctly:
```javascript
<Autolink text={'This is some text\nwith some newlines\nto see what happens'} />
```

**Comment by XaviSmith** [comment]
Looked more into this and it turns out there was a function elsewhere that stripped out \r's and \n's before passing it to autolink

Issue is resolved, I did notice that I would get a crash if i did something like
```
<Autolink text={'This is some text
with some newlines
to see what happens'} />
```

but that may just have more to do with how react-native handles strings
