### ISSUE TITLE
prop to allow truncation of email

### ISSUE THREAD

**Issue by AndBroPLAYipp** [joshswan/react-native-autolink#49]
I would love to see a prop to stop truncation of email addresses.

**Suggestion:** 
`emailTruncate?: false`

**Comment by joshswan** [comment]
Using `truncate={0}` will disable link truncation. Or do you want to configure truncation depending on the type of link? If that's the case, my initial inclination is to suggest using `renderLink` as adding `truncateEmail`, `truncateHashtag`, etc. seems a bit much.

Let me know what you think.

**Comment by AndBroPLAYipp** [comment]
I was more looking in to type of link adding the ability to disable it for mailto primarily.
Problem i have is that the strings are not static and tend to be different everytime and i found it little bit ugly and confusive with the truncation of email addresses. This idea of turning it off stem primarily from users started to ask why the emails were cut off in the middle reporting it as a bug.

As a side note i can also see a usage of turning it off for hashtags as well.

**Comment by joshswan** [comment]
I'm curious why you don't just want to disable truncation entirely. Is there a type of link that you do want to truncate?

I'm actually considering disabling truncation by default in v5.

**Comment by joshswan** [comment]
`v4.0.0` (currently release candidate) disabled truncation by default (use `truncate={32}` for previous behavior). The `truncate` function can be imported and combined with `renderLink` for complete flexibility.
