### ISSUE TITLE
Emoji prefixed urls cause app to crash

### ISSUE THREAD

**Issue by okwast** [joshswan/react-native-autolink#50]
Hey there,

first of all thank you for the great library.
We are using it for quite some time and are happy with it 🙂 

Sadly we found an issue that we think should be addressed.

We recently had in one of our texts something like this: `👉www.google.com`
The issue is it detects the url **INCLUDING** the emoji.
This results in the url that is tried to be opened to be `http://👉www.google.com` which causes a crash.

Until now I was not perfectly sure where exactly the matching happens/comes from that also detects the emoji as part of the string.

### What needs to be done

The preferred solution is to detect the url without the preceding emoji.
If that is not possible at least the app should not crash when trying to open this.

### What I did so far

At least I created a branch in which there is a test exactly showing what I think the result should look like.
See: https://github.com/okwast/react-native-autolink/tree/emoji-prefixed-urls

I would be happy to help with the fix, but it would be great to get some hints on where the matching takes place and why it includes the emoji.
To be honest any help is appreciated 🙂 

Thanks in advance.

Oliver

**Comment by joshswan** [comment]
Closing this for now. Let me know if you have further details on the crash.

**Comment by okwast** [comment]
Hey, sorry for the late response. I'm on vacation right now. Will do more research, when I'm back and will reach back to you then.

**Comment by joshswan** [comment]
No worries. Enjoy your vacation and let me know if you discover anything when you're back :)

**Comment by okwast** [comment]
Hey @joshswan,

I'm back. Thank you for your response.
Actually you are right.
My test was stupid and I didn't realize that it is the [in app browser]() that crashes when trying to open the URL.
It even is an iOS issue, because the SafariViewController does not work properly there and just quits.

I will now have a look at the in app browser trying to try catch something to prevent the crash.

Sorry for creating the ticket with wrong assumptions.

Have a nice day ☀️
