### ISSUE TITLE
Handle specific press on multiple hashtags

### ISSUE THREAD

**Issue by andrefangeloni** [joshswan/react-native-autolink#52]
Hi there,
When the text has multiple hashtag, how could I know witch of them was pressed?
e.g: 
Nice job!
#foo #bar

I'd like to do a feature likes Instagram, search for specific hashtag, but onPress is generic.
Thanks

**Comment by joshswan** [comment]
Check out the docs. You'll see [onPress](https://github.com/joshswan/react-native-autolink#onpress) receives two arguments: the constructed URL and a Match object that you can use to customize behavior as you please.

Also, linking hashtags to instagram also doesn't really need onPress at all. This should be sufficient:

```javascript
<Autolink
  text="#foo #bar"
  hashtag="instagram"
/>
```
