### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by gregfenton** [joshswan/react-native-autolink#56]
1. Unclear as to what setting `url={true}` actually enables.  Is it equivalent to `{schemeMatches: true, wwwMatches: true, tldMatches: true}`, or a subset of that, or something else entirely?
2. Is there a way to have text by hyperlinkable similar to what you can do in markdown:
```md
  [this is clickable](https://google.com/)
```
3. For telephone numbers, the README seems to indicate that `tel:{phone}` is a thing.  Does this mean it requires the `tel:` prefix, or that it at least recognizes & handles that prefix?

**Comment by joshswan** [comment]
1. Yes, `url={true}` is identical to `{schemeMatches: true, wwwMatches: true, tldMatches: true}`. The more-verbose second option is simply there for customizability.
2. That's not really the point of this library as it's really intended to create links in unstructured / user-generated text. If you're going to have people input markdown, just use a markdown parser in my opinion. That said, should be easy to implement using the new custom matchers functionality. I believe one of the examples either in the README or the related PR did something similar.
3. `tel:{number}` and `sms:{number}` are examples of the links generated when the `phone` option is used.
