### ISSUE TITLE
Link within text - simple use case

### ISSUE THREAD

**Issue by gran33** [joshswan/react-native-autolink#61]
Hey, 
Thanks for awesome lib! 

I'm trying to have super simple terms & use text, something like this: 
![PHOTO-2021-08-30-10-39-05](https://user-images.githubusercontent.com/1650967/131303622-07d22f4b-7f73-4fae-b942-acdaf857bf6e.jpg)

Can't find how to do this in the docs...
I'm trying to rename the actual link to clickable text.

Any assist? 

Thanks in advance.

**Comment by joshswan** [comment]
Technically should be achievable using custom matchers or normal URLs combined with a custom renderLink function.

That said, as mentioned in many other issues, the point of this library is to link text in unstructured / user-generated content. If you're creating an interface that you control, it'd be much easier to just manually add buttons and links with their respective handlers.
