### ISSUE TITLE
Matched text gets bugged

### ISSUE THREAD

**Issue by xKRUTOIx** [joshswan/react-native-autolink#67]
Hello everyone, sometimes matched text gets modified and to make it look good I have to remount the component.

I have a modal where people can send messages and I use this awesome library to highlight urls, mentions, phones and emails.

This is original text:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/6790512/201866782-7117e3d0-0b0d-400c-b5d2-6d1b63e99cb2.png">

This is bugged text(to get the original text back I have to hide and show the modal again):
<img width="269" alt="image" src="https://user-images.githubusercontent.com/6790512/201866854-5e2271b5-de8f-4e7e-99d3-0d34be6c79f4.png">

Using the latest version of the lib
```
"react-native-autolink": "^4.0.0",
```

So far this has been happening only with phone numbers matched by my custom matcher so maybe something is wrong with it:
```
matchers={[
                        {
                            pattern:
                                // matches phone numbers
                                /[+]?[0-9]?\s?[(]?[0-9]{3}[)]?[-\s.]?[0-9]{3}[-\s.]?[0-9]{2}[-]?[0-9]{2,4}/g,
                            style: {
                                textDecorationLine: 'underline',
                            },
                            onPress: match => {
                                copyWithToast(
                                    match.getReplacerArgs()[0],
                                    Toast.BOTTOM,
                                );
                            },
                        },
                    ]}
```

Also I had looked through the issues and couldn't find anything similar 🤔

**Comment by joshswan** [comment]
Is the `phone` prop enabled or disabled? If it's only happening with phone numbers, my assumption is the built-in phone matcher is replacing those strings with match placeholders (so they can later be wrapped with "links") and then your custom matcher regex is matching those placeholders and altering them.

If that doesn't help, can you post a full example of your Autolink component usage and some same text.

**Comment by xKRUTOIx** [comment]
@joshswan ohhhh....yeah, `phone` prop is enabled. 

Initially I wanted to highlight phone numbers and had enabled this property but turns out that it does not match all phones formats I need and I decided to "patch" it with my additional regexp and looks like they're conflicting indeed.

Thanks, that's a great guess and I think you're right.

I will disable it then and solve the problem only using my custom matcher.
