### ISSUE TITLE
getReplacementArgs

### ISSUE THREAD

**Issue by nahcnats** [joshswan/react-native-autolink#68]
if my text is  "the cow jump over `[test](www.google.com)` and found gold". When I use the following:

onPress: (match) => {
        console.log(match.getReplacerArgs()[2])
}

It returns something like @__Element etc. Why? Where did I do wrong? Appreciate your assistance.

**Comment by joshswan** [comment]
My suggestion would be to avoid using `getReplacerArgs` directly and instead use `match.matchedText`, `match.getAnchorText()`, `match.getType()`, etc. depending on what you're trying to accomplish.
