### ISSUE TITLE
Autolink adding // on email in Android

### ISSUE THREAD

**Issue by rrawla** [joshswan/react-native-autolink#7]
Hi ,
Thanks for the awesome utility. I was trying it on Android and for email even if I set email={true}
autolink is adding // in the email address for Gmail, I'm using genymotion with Android v 4.4 api 19 

Thanks!
Rahul

**Comment by joshswan** [comment]
The URI schemes for phone and email links have been updated so this should be fixed in v0.5.0, which was just published to npm. Thanks for pointing it out!
