### ISSUE TITLE
Do not automatically break the line if you have previously entered a newline

### ISSUE THREAD

**Issue by luanzt** [joshswan/react-native-autolink#72]
I think we have an issue: 
When I enter paragraphs with InputText, after rendering with AutoLink it seems to be removing break lines in the text.

**Comment by joshswan** [comment]
Please provide some example code and steps to reproduce. The following code that contains newlines renders correctly with newlines:

```typescript
<Autolink
  text={'https://github.com\n\nParagraph 2\n\nParagraph 3'}
  url
/>
```

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-07-18 at 11 17 10](https://github.com/joshswan/react-native-autolink/assets/11714764/271ff566-4997-4662-84d0-436e45d343d5)
