### ISSUE TITLE
render() for CustomMatchers

### ISSUE THREAD

**Issue by muonsei** [joshswan/react-native-autolink#73]
Is there a way to use a custom component with a CustomMatcher, something like `renderLink()` as seen [here](https://github.com/joshswan/react-native-autolink#renderlink)? I'm looking into using something like MotiPressable or MotiLink on a CustomMatcher since I need something that cannot be handled by just `onPress()` to control each matcher's behavior.

**Comment by joshswan** [comment]
Wasn't possible before but just added it in v4.2.0 as it seems like a super useful option.

CustomMatch objects now take an optional `renderLink` function (same signature as the main one) that can be used to override the rendering of just that one custom match.
