### ISSUE TITLE
I set the matchers property and it doesn't work on Android and iOS. Neither onPress nor style works.

### ISSUE THREAD

**Issue by Qy742698** [joshswan/react-native-autolink#77]
I set the matchers property and it doesn't work on Android and iOS. Neither onPress nor style works.

This is the usage：
<Autolink
                text="This is the string to parse for urls (https://github.com/joshswan/react-native-autolink), phone numbers (415-555-5555), emails (837185575@qq.com), mentions/handles (@twitter), and hashtags (#exciting)"
                email
                phone="text"
                url
                linkStyle={{ color: 'blue' }}
                hashtag = {false}
                 matchers={[
                    {
                        pattern: /\bhttps:\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[A-Z0-9+&@#\/%=~_|]/g,
                        style: { color: "bule", backgroundColor: 'red' },
                        getLinkText: (replacerArgs) => `@${replacerArgs[1]}`,
                        onPress: (match) => {
                            navigate('userProfile', { userId: match.getReplacerArgs()[2] });
                        },
                    },
                ]}
            />

**Comment by joshswan** [comment]
Your regex pattern doesn't match anything in the string. I highly recommend using a site like [regex101.com](https://regex101.com/) to get your pattern right before trying to debug in an app.

**Comment by Qy742698** [comment]
But I can't use the regular expression in your demo.

**Comment by joshswan** [comment]
Then don't use the one in the demo, the whole point of _custom_ matchers is that you can build custom functionality. Craft your own regex.

**Comment by Qy742698** [comment]
How do I use the matchers property?

**Comment by Qy742698** [comment]
matchers={[
                    {
                        pattern:  /<text>.*?<\/text>/gm,
                        style: { color: "bule", backgroundColor: 'red' },
                        getLinkText: (replacerArgs) =>
                        ' ' + replacerArgs[0].slice(1, 2),
                        onPress: (match) => {
                            navigate('userProfile', { userId: match.getReplacerArgs()[2] });
                        },
                    },
                ]}
I set this up and it still doesn't work.

**Comment by Qy742698** [comment]
matchers={[
{
pattern: /<text>.*?</text>/gm,
style: { color: "bule", backgroundColor: 'red' },
getLinkText: (replacerArgs) =>
' ' + replacerArgs[0].slice(1, 2),
onPress: (match) => {
navigate('userProfile', { userId: match.getReplacerArgs()[2] });
},
},
]}

**Comment by joshswan** [comment]
@Qy742698 Do not spam other users in unrelated issues.

This is a working example for custom matchers. Beyond that, you need to either develop your own regex or revert to just using the built-in functionality instead of trying to build something custom.

```typescript
<Autolink
  text="Example text with a user link to @[John Doe](1234) within"
  matchers={[
    {
      pattern: /@\[([^[]*)]\(([^(^)]*)\)/g,
      style: { color: '#ff00ff' },
      getLinkText: (replacerArgs) => `@${replacerArgs[1]}`,
      onPress: (match) => {
        console.log('userId', match.getReplacerArgs()[2]);
      },
    },
  ]}
/>
```

**Comment by Qy742698** [comment]
It's solved
