### ISSUE TITLE
onpress does not take effect

### ISSUE THREAD

**Issue by Qy742698** [joshswan/react-native-autolink#79]
I'm using the onpress method, which, judging by the mention property, won't display the Alert.alert ('Mention pressed!') ;

<Autolink
  text={text}
  onPress={(url, match) => {
    switch (match.getType()) {
      case 'mention':
        Alert.alert('Mention pressed!');
      default:
        Alert.alert('Link pressed!');
    }
  }}
/>

**Comment by joshswan** [comment]
You are missing both a `break` in your `switch` AND props to control mentions and other types of links (i.e.  the `mention`, `url`, etc. props).

Please stop opening issues without clear reproductions that have to do with this library and not your code. This is not a support forum.

https://github.com/user-attachments/assets/86d236bf-cca3-4bcb-a352-94369804a0fe
