### ISSUE TITLE
onPress

### ISSUE THREAD

**Issue by voidException** [joshswan/react-native-autolink#8]
Thanks for your job, but I hava  a question,how to custom the onPress props ,such  as  when i click "@twitter" I can go his home page ? I need help ,can you give me a  example?thanks

<AutoLink
       text="This is the string to parse for urls (https://github.com/joshswan/react-native-autolink), phone   
                          twitter handles (@twitter), and hashtags (#exciting)"
        hashtag="instagram"
        twitter={true}
       onPress={ ?} />

how  to  get the  value   "twitter" ?  in the onPress

**Comment by joshswan** [comment]
```javascript
onPress={(link, match) => {
  const type = match.getType(); // email, hashtag, phone, twitter, or url
})
```
See the README for more info. The match object details can be found here: http://gregjacobs.github.io/Autolinker.js/docs/#!/api/Autolinker.match.Match
