### ISSUE TITLE
onLongPress doesn't work either.

### ISSUE THREAD

**Issue by Qy742698** [joshswan/react-native-autolink#80]
const onLongPress = ((url: any, match: any) => {
        switch (match.getType()) {
            case 'mention':
                Linking.openURL(url)
                break
            default:
                Linking.openURL('https://www.baidu.com')
        }
    })

**Comment by joshswan** [comment]
Works fine. Again, please stop opening issues without clear reproductions that relate to issues with the library.


https://github.com/user-attachments/assets/2963907b-c8c4-440a-85d1-2a408a16bec6
