### ISSUE TITLE
Unable to resolve "./truncate" from "node_modules\react-native-autolink\dist\index.js"

### ISSUE THREAD

**Issue by AndrianarivoAlpha** [joshswan/react-native-autolink#83]
[Error: undefined Unable to resolve module ./truncate from C:\Users\Alpha\Documents\Devs\visited\client\node_modules\react-native-autolink\dist\index.js:

None of these files exist:
  * node_modules\react-native-autolink\dist\truncate(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  * node_modules\react-native-autolink\dist\truncate
  10 | export * from './CustomMatch'; 
  11 | export * from './matchers';    
> 12 | export { truncate } from './truncate';
     |                           ^    
  13 | export * from './urls';        
  14 | export default Autolink;       
  15 |]
  
  I have this error using it in expo

**Comment by joshswan** [comment]
I just checked with a fresh expo install with the latest version of this package and it all works fine. `dist/truncate.js` is definitely there. I'd recommend double-checking your install for any issues.


<img width="246" alt="Screenshot 2024-12-06 at 12 32 27 PM" src="https://github.com/user-attachments/assets/f46d8731-3cc9-4d26-869c-81cb08fc5158">

![Simulator Screenshot - iPhone 16 - 2024-12-06 at 12 32 39](https://github.com/user-attachments/assets/10d140af-8fe1-4b9f-937e-184676b7d102)
