### ISSUE TITLE
Facebook hashtag link not working iOS

### ISSUE THREAD

**Issue by zachgibson** [joshswan/react-native-autolink#9]
Seems that the scheme has changed to: fb://hashtag/%s?name=%s&id=%s according to this [stackoverflow](http://stackoverflow.com/questions/5707722/what-are-all-the-custom-url-schemes-supported-by-the-facebook-iphone-app/5707825#answer-30231726) thread.

**Comment by joshswan** [comment]
Sorry it took me so long to get to this. I agree that the current link isn't working, however, I just tried the new scheme you provided and that didn't seem to work either. Maybe I'm doing something wrong. Have you tested out the new scheme?

**Comment by zachgibson** [comment]
Yeah I can't get it to work either. I'm having trouble finding any documentation on this.

**Comment by joshswan** [comment]
Same here. None of it is officially supported so it's not surprising that there's little info. When I have some time, I might go through some of the other options (fb://search ?) to see if I can get something to work but I'm not optimistic.

**Comment by zachgibson** [comment]
Yeah, makes sense. Thanks anyways man.
